routes:
  /:
    template: index
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account

collections:
  /blog/:
    permalink: /{slug}/
    template: blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
